/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import processing.core.PApplet;


class AppTest {
    @Test 
    public void simpleTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }

    @Test
    public void setupTest() {
        App app = new App();
        PApplet.runSketch(new String[] {"App"}, app);
        app.setup();
        app.draw();
    }

    @Test 
    public void keyPressedTest() {
        App app = new App();
        app.game.waka = new Waka(100, 100, null, null, null, null, null);
        app.keyCode = app.RIGHT;
        app.keyPressed();
        assertEquals(app.game.waka.nextMove, "right");
        app.keyCode = app.LEFT;
        app.keyPressed();
        assertEquals(app.game.waka.nextMove, "left");
        app.keyCode = app.UP;
        app.keyPressed();
        assertEquals(app.game.waka.nextMove, "up");
        app.keyCode = app.DOWN;
        app.keyPressed();
        assertEquals(app.game.waka.nextMove, "down");
    }

}

